[build]
  # Base directory for the build
  base = "apps/web"
  
  # Build command - install dependencies from root and build the web app
  command = "cd ../.. && yarn install --frozen-lockfile && yarn turbo run build --filter=cipherchat-web..."
  
  # Publish directory - Next.js static export output
  publish = ".next"

[build.environment]
  # Node version
  NODE_VERSION = "18"
  # Yarn version
  YARN_VERSION = "1.22.19"

# Environment variables (set these in Netlify dashboard)
# NEXT_PUBLIC_API_URL - Your backend API URL (e.g., https://your-app.onrender.com)
# NEXT_PUBLIC_SOCKET_URI - Your backend socket URL
